import { JudgeDemoScenario, LivestockItem, PharmaProduct, Region, Report } from './types';

export const INITIAL_REGIONS: Region[] = [
  // Nashik
  { district: 'Nashik', block: 'Nashik Block-1', village: 'Nashik Block-1 Village-1', latitude: 20.13112, longitude: 73.79635 },
  { district: 'Nashik', block: 'Nashik Block-1', village: 'Nashik Block-1 Village-2', latitude: 20.03939, longitude: 73.82974 },
  { district: 'Nashik', block: 'Nashik Block-2', village: 'Nashik Block-2 Village-1', latitude: 20.04227, longitude: 73.8551 },
  { district: 'Nashik', block: 'Nashik Block-2', village: 'Nashik Block-2 Village-2', latitude: 20.05561, longitude: 73.83549 },
  { district: 'Nashik', block: 'Nashik Block-3', village: 'Nashik Block-3 Village-1', latitude: 20.08542, longitude: 73.64465 },
  // Pune
  { district: 'Pune', block: 'Pune Block-1', village: 'Pune Block-1 Village-1', latitude: 18.37661, longitude: 73.86979 },
  { district: 'Pune', block: 'Pune Block-1', village: 'Pune Block-1 Village-2', latitude: 18.40183, longitude: 73.88933 },
  { district: 'Pune', block: 'Pune Block-2', village: 'Pune Block-2 Village-1', latitude: 18.53914, longitude: 73.68951 },
  { district: 'Pune', block: 'Pune Block-2', village: 'Pune Block-2 Village-2', latitude: 18.60958, longitude: 73.76841 },
  // Kolhapur
  { district: 'Kolhapur', block: 'Kolhapur Block-1', village: 'Kolhapur Block-1 Village-1', latitude: 16.705, longitude: 74.2433 },
  { district: 'Kolhapur', block: 'Kolhapur Block-2', village: 'Kolhapur Block-2 Village-1', latitude: 16.732, longitude: 74.298 },
  // Sambhajinagar (Aurangabad)
  { district: 'Sambhajinagar', block: 'Sambhajinagar Block-1', village: 'Sambhajinagar Block-1 Village-1', latitude: 19.8762, longitude: 75.3433 },
  { district: 'Sambhajinagar', block: 'Sambhajinagar Block-2', village: 'Sambhajinagar Block-2 Village-1', latitude: 19.912, longitude: 75.389 },
  // Nagpur
  { district: 'Nagpur', block: 'Nagpur Block-1', village: 'Nagpur Block-1 Village-1', latitude: 21.1458, longitude: 79.0882 },
  { district: 'Nagpur', block: 'Nagpur Block-2', village: 'Nagpur Block-2 Village-1', latitude: 21.178, longitude: 79.123 },
  // Amravati
  { district: 'Amravati', block: 'Amravati Block-1', village: 'Amravati Block-1 Village-1', latitude: 20.932, longitude: 77.7523 },
  { district: 'Amravati', block: 'Amravati Block-2', village: 'Amravati Block-2 Village-1', latitude: 20.965, longitude: 77.798 },
];

export const INITIAL_LIVESTOCK: LivestockItem[] = [
  {
    id: 'live-1',
    title: 'Gir Cow (Purebred A2 Dairy)',
    marathiTitle: 'गीर गाय (शुद्ध देशी A2 दूध)',
    species: 'cattle',
    breed: 'Gir (Kathiawari)',
    ageYears: 3.5,
    gender: 'Female',
    lactationOrWeight: '16-18 Litres/day (2nd Lactation)',
    price: 68000,
    originalPrice: 75000,
    imageUrl: 'https://images.unsplash.com/photo-1546445317-29f4545e9d53?auto=format&fit=crop&w=800&q=80',
    district: 'Pune',
    village: 'Pune Block-1 Village-1',
    sellerName: 'Kailas Jadhav (Certified Dairy Farmer)',
    sellerVerified: true,
    featured: true,
    status: 'Available',
    healthPassport: {
      rfidTag: 'IN-MH-2026-8812',
      issueDate: '2026-08-15',
      vetOfficerName: 'Dr. Ramesh Deshmukh, MVSc',
      vetRegistrationNo: 'MH-VET-9021',
      quarantineClearance: true,
      biosecurityRating: 'A+',
      vaccinations: [
        { disease: 'Foot & Mouth Disease (FMD)', dateAdministered: '2026-05-10', batchNo: 'FMD-982B', validUntil: '2027-05-10', status: 'Active' },
        { disease: 'Lumpy Skin Disease (LSD)', dateAdministered: '2026-06-22', batchNo: 'LSD-441K', validUntil: '2027-06-22', status: 'Active' },
        { disease: 'Hemorrhagic Septicemia (HS)', dateAdministered: '2026-04-18', batchNo: 'HS-109P', validUntil: '2027-04-18', status: 'Active' },
        { disease: 'Brucellosis (Strain 19)', dateAdministered: '2024-02-12', batchNo: 'BR-330A', validUntil: 'Lifetime', status: 'Active' },
      ],
      healthCheckLogs: [
        { date: '2026-08-15', temperature: '38.6°C', vitalSigns: 'Optimal, Clear Lung Sounds, Clean Eyes', status: 'Healthy' },
        { date: '2026-07-02', temperature: '38.4°C', vitalSigns: 'Normal lactation, Rumen motility active', status: 'Healthy' },
      ],
    },
  },
  {
    id: 'live-2',
    title: 'Murrah Buffalo (High Fat Yield)',
    marathiTitle: 'मुर्रा म्हैस (उच्च फॅट दूध)',
    species: 'buffalo',
    breed: 'Murrah Elite',
    ageYears: 4,
    gender: 'Female',
    lactationOrWeight: '18-20 Litres/day (Fat 7.8%)',
    price: 88000,
    originalPrice: 95000,
    imageUrl: 'https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?auto=format&fit=crop&w=800&q=80',
    district: 'Kolhapur',
    village: 'Kolhapur Block-1 Village-1',
    sellerName: 'Patil Agro Livestock Co-op',
    sellerVerified: true,
    featured: true,
    status: 'Available',
    healthPassport: {
      rfidTag: 'IN-MH-2026-9430',
      issueDate: '2026-08-20',
      vetOfficerName: 'Dr. Sunita Patil, BVSc',
      vetRegistrationNo: 'MH-VET-8834',
      quarantineClearance: true,
      biosecurityRating: 'A+',
      vaccinations: [
        { disease: 'Foot & Mouth Disease (FMD)', dateAdministered: '2026-06-01', batchNo: 'FMD-102C', validUntil: '2027-06-01', status: 'Active' },
        { disease: 'Black Quarter (BQ)', dateAdministered: '2026-05-15', batchNo: 'BQ-551M', validUntil: '2027-05-15', status: 'Active' },
        { disease: 'Hemorrhagic Septicemia (HS)', dateAdministered: '2026-05-15', batchNo: 'HS-882T', validUntil: '2027-05-15', status: 'Active' },
      ],
      healthCheckLogs: [
        { date: '2026-08-20', temperature: '38.2°C', vitalSigns: 'Cardiovascular normal, no tick infestation', status: 'Healthy' },
      ],
    },
  },
  {
    id: 'live-3',
    title: 'Osmanabadi Goat Breeding Pair',
    marathiTitle: 'उस्मानाबादी शेळी जोडी (पैदास योग्य)',
    species: 'goat',
    breed: 'Osmanabadi Pure',
    ageYears: 1.5,
    gender: 'Female',
    lactationOrWeight: '42 kg Live Weight (Twin Birth Record)',
    price: 24500,
    originalPrice: 28000,
    imageUrl: 'https://images.unsplash.com/photo-1524024973431-2ad916746881?auto=format&fit=crop&w=800&q=80',
    district: 'Sambhajinagar',
    village: 'Sambhajinagar Block-1 Village-1',
    sellerName: 'Vikas Shinde Goat Farm',
    sellerVerified: true,
    featured: false,
    status: 'Available',
    healthPassport: {
      rfidTag: 'IN-MH-2026-3391',
      issueDate: '2026-08-28',
      vetOfficerName: 'Dr. Anand Joshi, MVSc',
      vetRegistrationNo: 'MH-VET-7719',
      quarantineClearance: true,
      biosecurityRating: 'A',
      vaccinations: [
        { disease: 'PPR (Peste des Petits Ruminants)', dateAdministered: '2026-03-10', batchNo: 'PPR-992X', validUntil: '2029-03-10', status: 'Active' },
        { disease: 'Enterotoxaemia (ET)', dateAdministered: '2026-07-04', batchNo: 'ET-110L', validUntil: '2027-07-04', status: 'Active' },
        { disease: 'Goat Pox', dateAdministered: '2026-04-12', batchNo: 'GP-702K', validUntil: '2027-04-12', status: 'Active' },
      ],
      healthCheckLogs: [
        { date: '2026-08-28', temperature: '39.0°C', vitalSigns: 'Active feeding, sleek coat, healthy mucous membranes', status: 'Healthy' },
      ],
    },
  },
  {
    id: 'live-4',
    title: 'Saffolk Cross Sheep Flock (5 Ewes)',
    marathiTitle: 'सफोक क्रॉस मेंढी गट (५ मेंढ्या)',
    species: 'sheep',
    breed: 'Deccani x Saffolk',
    ageYears: 2,
    gender: 'Female',
    lactationOrWeight: '38 kg Avg Live Weight (Wool & Mutton)',
    price: 48000,
    imageUrl: 'https://images.unsplash.com/photo-1484557052118-f32bd25b45b5?auto=format&fit=crop&w=800&q=80',
    district: 'Pune',
    village: 'Pune Block-2 Village-1',
    sellerName: 'Dhangar Agro Herds',
    sellerVerified: true,
    featured: false,
    status: 'Available',
    healthPassport: {
      rfidTag: 'IN-MH-2026-5520',
      issueDate: '2026-08-10',
      vetOfficerName: 'Dr. Ramesh Deshmukh, MVSc',
      vetRegistrationNo: 'MH-VET-9021',
      quarantineClearance: true,
      biosecurityRating: 'A',
      vaccinations: [
        { disease: 'Enterotoxaemia (ET)', dateAdministered: '2026-06-15', batchNo: 'ET-401Q', validUntil: '2027-06-15', status: 'Active' },
        { disease: 'Sheep Pox', dateAdministered: '2026-05-18', batchNo: 'SP-228J', validUntil: '2027-05-18', status: 'Active' },
      ],
      healthCheckLogs: [
        { date: '2026-08-10', temperature: '39.1°C', vitalSigns: 'All 5 animals clear of ectoparasites, de-wormed', status: 'Healthy' },
      ],
    },
  },
  {
    id: 'live-5',
    title: 'Kadaknath Purebred Backyard Flock (20 Birds)',
    marathiTitle: 'कडकनाथ मूळ जात कुक्कुट गट (२० पक्षी)',
    species: 'poultry',
    breed: 'Kadaknath (Black Meat)',
    ageYears: 0.6,
    gender: 'Female',
    lactationOrWeight: '1.4 kg average live weight',
    price: 9500,
    imageUrl: 'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?auto=format&fit=crop&w=800&q=80',
    district: 'Nagpur',
    village: 'Nagpur Block-1 Village-1',
    sellerName: 'Vidarbha Organic Poultry',
    sellerVerified: true,
    featured: false,
    status: 'Available',
    healthPassport: {
      rfidTag: 'IN-MH-2026-7714',
      issueDate: '2026-08-25',
      vetOfficerName: 'Dr. Sneha Khobragade, MVSc',
      vetRegistrationNo: 'MH-VET-6641',
      quarantineClearance: true,
      biosecurityRating: 'A+',
      vaccinations: [
        { disease: 'Ranikhet Disease (ND - Lasota)', dateAdministered: '2026-07-10', batchNo: 'ND-881L', validUntil: '2026-11-10', status: 'Active' },
        { disease: 'Infectious Bursal Disease (Gumboro)', dateAdministered: '2026-07-22', batchNo: 'IBD-302B', validUntil: '2027-07-22', status: 'Active' },
      ],
      healthCheckLogs: [
        { date: '2026-08-25', temperature: '41.2°C', vitalSigns: 'Alert, bright comb, no respiratory rales', status: 'Healthy' },
      ],
    },
  },
  {
    id: 'live-6',
    title: 'Sahiwal Dairy Cow (Disease Resistant)',
    marathiTitle: 'साहिवाल देशी गाय (रोगप्रतिकारक)',
    species: 'cattle',
    breed: 'Sahiwal',
    ageYears: 3,
    gender: 'Female',
    lactationOrWeight: '14-16 Litres/day (A2 Beta-Casein)',
    price: 62000,
    originalPrice: 69000,
    imageUrl: 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&w=800&q=80',
    district: 'Amravati',
    village: 'Amravati Block-1 Village-1',
    sellerName: 'Gaurakshak Agro Farm',
    sellerVerified: true,
    featured: false,
    status: 'Available',
    healthPassport: {
      rfidTag: 'IN-MH-2026-2180',
      issueDate: '2026-08-18',
      vetOfficerName: 'Dr. Pravin Gawande, BVSc',
      vetRegistrationNo: 'MH-VET-5512',
      quarantineClearance: true,
      biosecurityRating: 'A+',
      vaccinations: [
        { disease: 'Foot & Mouth Disease (FMD)', dateAdministered: '2026-05-12', batchNo: 'FMD-440T', validUntil: '2027-05-12', status: 'Active' },
        { disease: 'Lumpy Skin Disease (LSD)', dateAdministered: '2026-06-18', batchNo: 'LSD-912A', validUntil: '2027-06-18', status: 'Active' },
      ],
      healthCheckLogs: [
        { date: '2026-08-18', temperature: '38.5°C', vitalSigns: 'Clean respiratory tract, healthy udder', status: 'Healthy' },
      ],
    },
  },
];

export const INITIAL_PHARMA: PharmaProduct[] = [
  {
    id: 'pharma-resp-kit',
    name: 'Bovine Respiratory Distress Emergency Pack',
    marathiName: 'श्वसनरोग तातडीचा उपचार किट',
    category: 'Emergency Kit',
    price: 1450,
    originalPrice: 1800,
    rating: 4.9,
    reviewCount: 142,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80',
    dosage: 'Includes Meloxicam + Paracetamol Bolus (10 strips), Bronchodilator Syrup (500ml), and Oral Rehydration Salt (5 sachets)',
    targetSpecies: ['cattle', 'buffalo', 'goat', 'sheep'],
    symptomIndications: ['respiratory_distress', 'coughing', 'nasal_discharge', 'fever'],
    description: 'Rapid veterinary stabilization bundle formulated for acute broncho-pneumonia and respiratory distress in livestock herds.',
    inStock: true,
    badge: '🚨 High-Concern Triage Match',
    isEmergencyBundle: true,
  },
  {
    id: 'pharma-lumpy-care',
    name: 'Lumpy-Care Epidemic Antiseptic & Wound Spray Pack',
    marathiName: 'लम्पी त्वचा रोग प्रतिबंधक औषध संच',
    category: 'Emergency Kit',
    price: 890,
    originalPrice: 1100,
    rating: 4.8,
    reviewCount: 98,
    imageUrl: 'https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?auto=format&fit=crop&w=800&q=80',
    dosage: 'Includes herbal skin spray (500ml), fly-repellent ointment (200g), and immunity booster bolus (20 tabs)',
    targetSpecies: ['cattle', 'buffalo'],
    symptomIndications: ['skin_lesions', 'swelling', 'fever', 'loss_of_appetite'],
    description: 'Comprehensive topical and internal antiseptic therapy for cutaneous nodules, secondary fly-strike prevention, and immune recovery.',
    inStock: true,
    badge: 'Maharashtra Outbreak Special',
    isEmergencyBundle: true,
  },
  {
    id: 'pharma-electrolytes',
    name: 'Bio-Electrolyte Pro Energy & Rumen Rehydrator (1 kg)',
    marathiName: 'बायो-इलेक्ट्रोलाइट ऊर्जा व डीहायड्रेशन पावडर',
    category: 'Electrolyte & Tonics',
    price: 340,
    originalPrice: 420,
    rating: 4.9,
    reviewCount: 310,
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&w=800&q=80',
    dosage: '50g twice daily mixed in lukewarm drinking water or gruel',
    targetSpecies: ['cattle', 'buffalo', 'goat', 'sheep'],
    symptomIndications: ['weakness', 'diarrhea', 'loss_of_appetite'],
    description: 'Fortified with Potassium Chloride, Sodium Citrate, Glycine, and Dextrose to reverse dehydration and hypovolemic shock.',
    inStock: true,
  },
  {
    id: 'pharma-broad-antibiotic',
    name: 'Vet-Clox Broad-Spectrum Antipyretic Bolus (12x4)',
    marathiName: 'व्हेट-क्लॉक्स ब्रॉड स्पेक्ट्रम ताप-गोळ्या',
    category: 'Antibiotic',
    price: 520,
    rating: 4.7,
    reviewCount: 88,
    imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=800&q=80',
    dosage: '1 bolus per 100 kg body weight for 3-5 consecutive days',
    targetSpecies: ['cattle', 'buffalo', 'goat', 'sheep'],
    symptomIndications: ['fever', 'weakness', 'swelling'],
    description: 'Veterinary prescription-grade formulation indicated for systemic bacterial infections and secondary bacterial prophylaxis.',
    inStock: true,
  },
  {
    id: 'pharma-vet-telepass',
    name: 'Immediate Tele-Veterinary Video Consultation Pass',
    marathiName: 'तातडीचा टेलिव्हेट व्हिडिओ सल्ला पास',
    category: 'Diagnostics',
    price: 199,
    originalPrice: 499,
    rating: 5.0,
    reviewCount: 422,
    imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
    dosage: 'Instant 15-minute live HD video consult with accredited Maharashtra State Veterinary Doctor + Digital Rx',
    targetSpecies: ['cattle', 'buffalo', 'goat', 'sheep', 'poultry'],
    symptomIndications: ['respiratory_distress', 'neurological_symptoms', 'sudden_death'],
    description: 'Instant remote clinical assessment, prescription generation, and official surveillance logging.',
    inStock: true,
    badge: 'Govt Subsidized (60% OFF)',
    isEmergencyBundle: true,
  },
  {
    id: 'pharma-dewormer',
    name: 'Albendazole + Ivermectin High-Potency De-wormer (100ml)',
    marathiName: 'जंतनाशक औषध (अल्बेंडाझोल + आयव्हरमेक्टिन)',
    category: 'Antibiotic',
    price: 280,
    rating: 4.8,
    reviewCount: 215,
    imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=800&q=80',
    dosage: '5-10 ml per 50 kg body weight orally before morning feeding',
    targetSpecies: ['cattle', 'buffalo', 'goat', 'sheep'],
    symptomIndications: ['loss_of_appetite', 'reduced_milk_production', 'weakness'],
    description: 'Eliminates roundworms, tapeworms, liver flukes, and external mange mites in dairy and small ruminants.',
    inStock: true,
  },
  {
    id: 'pharma-mineral-mix',
    name: 'Chelated Mineral Mixture & Vitamin AD3E (5 kg)',
    marathiName: 'चिलेटेड मिनरल मिक्स्चर (दुग्ध वाढ व प्रतिकार)',
    category: 'Electrolyte & Tonics',
    price: 680,
    originalPrice: 850,
    rating: 4.9,
    reviewCount: 512,
    imageUrl: 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?auto=format&fit=crop&w=800&q=80',
    dosage: '50-100g daily in dry feed or concentrate',
    targetSpecies: ['cattle', 'buffalo'],
    symptomIndications: ['reduced_milk_production', 'weakness'],
    description: 'High-bioavailability micro-minerals that boost daily milk output, coat gloss, and immunological resistance.',
    inStock: true,
  },
  {
    id: 'pharma-dipstick-test',
    name: 'Brucella & Mastitis Rapid Field Diagnostic Dipsticks (Pack of 20)',
    marathiName: 'ब्रुसेला व मस्टायटीस जलद तपासणी स्ट्रिप्स',
    category: 'Diagnostics',
    price: 750,
    originalPrice: 950,
    rating: 4.7,
    reviewCount: 64,
    imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
    dosage: '1 strip per milk / blood serum sample; color result in 2 minutes',
    targetSpecies: ['cattle', 'buffalo'],
    symptomIndications: ['reduced_milk_production', 'fever', 'swelling'],
    description: 'On-farm rapid diagnostic strips allowing milk collectors and dairy farmers to screen subclinical infections on the spot.',
    inStock: true,
  },
];

// Pre-seeded reports mirroring an active outbreak cluster in Nashik Block-2
export const INITIAL_REPORTS: Report[] = [
  {
    report_id: 101,
    date: '2026-09-02',
    district: 'Nashik',
    block: 'Nashik Block-2',
    village: 'Nashik Block-2 Village-1',
    species: 'cattle',
    number_affected: 8,
    number_deaths: 3,
    duration_days: 2,
    temperature: 40.5,
    notes: 'Severe respiratory distress, multiple animal collapse in morning.',
    symptoms: { fever: true, respiratory_distress: true, weakness: true, sudden_death: true },
    mortality_rate: 0.375,
    risk_level: 'HIGH',
  },
  {
    report_id: 102,
    date: '2026-09-02',
    district: 'Nashik',
    block: 'Nashik Block-2',
    village: 'Nashik Block-2 Village-1',
    species: 'cattle',
    number_affected: 6,
    number_deaths: 2,
    duration_days: 3,
    temperature: 40.2,
    notes: 'Same village herd showing rapid lethargy and foaming.',
    symptoms: { fever: true, respiratory_distress: true, coughing: true },
    mortality_rate: 0.333,
    risk_level: 'HIGH',
  },
  {
    report_id: 103,
    date: '2026-09-03',
    district: 'Nashik',
    block: 'Nashik Block-2',
    village: 'Nashik Block-2 Village-1',
    species: 'buffalo',
    number_affected: 5,
    number_deaths: 1,
    duration_days: 1,
    temperature: 40.8,
    notes: 'High fever and skin lesions observed.',
    symptoms: { fever: true, skin_lesions: true, loss_of_appetite: true },
    mortality_rate: 0.2,
    risk_level: 'HIGH',
  },
  {
    report_id: 104,
    date: '2026-09-03',
    district: 'Nashik',
    block: 'Nashik Block-2',
    village: 'Nashik Block-2 Village-2',
    species: 'cattle',
    number_affected: 4,
    number_deaths: 1,
    duration_days: 2,
    temperature: 39.8,
    notes: 'Adjacent village case reported by field vet.',
    symptoms: { fever: true, respiratory_distress: true, weakness: true },
    mortality_rate: 0.25,
    risk_level: 'HIGH',
  },
  {
    report_id: 105,
    date: '2026-09-01',
    district: 'Pune',
    block: 'Pune Block-1',
    village: 'Pune Block-1 Village-1',
    species: 'cattle',
    number_affected: 2,
    number_deaths: 0,
    duration_days: 3,
    temperature: 39.1,
    notes: 'Mild milk drop, isolated animals.',
    symptoms: { loss_of_appetite: true, reduced_milk_production: true },
    mortality_rate: 0.0,
    risk_level: 'LOW',
  },
  {
    report_id: 106,
    date: '2026-08-30',
    district: 'Kolhapur',
    block: 'Kolhapur Block-1',
    village: 'Kolhapur Block-1 Village-1',
    species: 'buffalo',
    number_affected: 3,
    number_deaths: 0,
    duration_days: 4,
    temperature: 39.0,
    notes: 'Routine seasonal check.',
    symptoms: { weakness: true },
    mortality_rate: 0.0,
    risk_level: 'LOW',
  },
  {
    report_id: 107,
    date: '2026-09-02',
    district: 'Sambhajinagar',
    block: 'Sambhajinagar Block-1',
    village: 'Sambhajinagar Block-1 Village-1',
    species: 'goat',
    number_affected: 4,
    number_deaths: 0,
    duration_days: 2,
    temperature: 39.6,
    notes: 'Mild coughing and nasal discharge.',
    symptoms: { coughing: true, nasal_discharge: true },
    mortality_rate: 0.0,
    risk_level: 'MEDIUM',
  },
  {
    report_id: 108,
    date: '2026-08-28',
    district: 'Nagpur',
    block: 'Nagpur Block-1',
    village: 'Nagpur Block-1 Village-1',
    species: 'poultry',
    number_affected: 15,
    number_deaths: 2,
    duration_days: 3,
    notes: 'Backyard flock lethargy.',
    symptoms: { weakness: true, diarrhea: true },
    mortality_rate: 0.133,
    risk_level: 'MEDIUM',
  },
];

export const JUDGE_DEMO_SCENARIOS: JudgeDemoScenario[] = [
  {
    id: 'demo-triage-override',
    title: 'Scenario 1: Critical Triage with Safety Override',
    subtitle: 'Demonstrates explainable ML + deterministic safety fallback',
    badge: 'AI Safety & Triage',
    icon: 'ShieldAlert',
    description: 'Pre-fills a clinical report with 12 affected cattle, 4 deaths (33% mortality), and acute respiratory distress. Triggers ML probability assessment and proves how safety rules override probabilistic models.',
    actionType: 'triage',
  },
  {
    id: 'demo-outbreak-nashik',
    title: 'Scenario 2: Emerging Epidemic in Nashik Block-2',
    subtitle: 'Demonstrates spatial-temporal escalation & risk index',
    badge: 'Surveillance & GIS',
    icon: 'Activity',
    description: 'Simulates a synchronized burst of 10 reports into Nashik Block-2. Elevates regional risk score from LOW to CRITICAL (84/100), recolors the hotspot map, and broadcasts emergency containment alerts.',
    actionType: 'outbreak',
  },
  {
    id: 'demo-health-passport',
    title: 'Scenario 3: RFID Health Passport & Safe Cattle Trade',
    subtitle: 'Demonstrates how commerce stops disease vectors',
    badge: 'E-Commerce & Trust',
    icon: 'CheckCircle2',
    description: 'Inspects a purebred Gir cow listing with digital RFID health passport (#IN-MH-2026-8812), showing quarantine clearance, vaccination history, and preventing infected livestock movement.',
    actionType: 'passport',
  },
];
